version: '3.7'

services:
  web:
    build: ./rest_project/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./rest_project/:/usr/src/rest_project/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=rest_project
      - POSTGRES_PASSWORD=rest_project
      - POSTGRES_DB=rest_project_db

volumes:
  postgres_data: